AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/SymbolArray:
  EnforcedStyle: brackets
Style/FormatStringToken:
  EnforcedStyle: template
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/GuardClause:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/SymbolProc:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true

Layout/LineLength:
  Max: 120
